INSERT INTO tb_categorias(nome) values ('livros');
INSERT INTO tb_categorias(nome) values ('laminas');
INSERT INTO tb_categorias(nome) values ('bebidas');
INSERT INTO tb_categorias(nome) values ('alimentos');
INSERT INTO tb_categorias(nome) values ('calçados');
INSERT INTO tb_categorias(nome) values ('eletrônicos');
INSERT INTO tb_categorias(nome) values ('roupas');
INSERT INTO tb_categorias(nome) values ('móveis');
INSERT INTO tb_categorias(nome) values ('brinquedos');
INSERT INTO tb_categorias(nome) values ('acessórios');
INSERT INTO tb_categorias(nome) values ('esportes');
INSERT INTO tb_categorias(nome) values ('instrumentos musicais');
INSERT INTO tb_categorias(nome) values ('beleza');
INSERT INTO tb_categorias(nome) values ('saúde');
INSERT INTO tb_categorias(nome) values ('casa');
INSERT INTO tb_categorias(nome) values ('jardinagem');
INSERT INTO tb_categorias(nome) values ('automóveis');
INSERT INTO tb_categorias(nome) values ('pet shop');
INSERT INTO tb_categorias(nome) values ('papelaria');
INSERT INTO tb_categorias(nome) values ('artesanato');
INSERT INTO tb_categorias(nome) values ('relógios');
INSERT INTO tb_categorias(nome) values ('jóias');
INSERT INTO tb_categorias(nome) values ('computadores');
INSERT INTO tb_categorias(nome) values ('telefones');
INSERT INTO tb_categorias(nome) values ('fotografia');
INSERT INTO tb_categorias(nome) values ('fitness');
INSERT INTO tb_categorias(nome) values ('cine e vídeo');
INSERT INTO tb_categorias(nome) values ('colecionáveis');
INSERT INTO tb_categorias(nome) values ('informática');
INSERT INTO tb_categorias(nome) values ('têxteis');
INSERT INTO tb_categorias(nome) values ('ferramentas');
INSERT INTO tb_categorias(nome) values ('hardware');
INSERT INTO tb_categorias(nome) values ('software');
INSERT INTO tb_categorias(nome) values ('eventos');
INSERT INTO tb_categorias(nome) values ('saúde e bem-estar');
INSERT INTO tb_categorias(nome) values ('entretenimento');
INSERT INTO tb_categorias(nome) values ('eletrodomésticos');
INSERT INTO tb_categorias(nome) values ('relacionamentos');
INSERT INTO tb_categorias(nome) values ('educação');
INSERT INTO tb_categorias(nome) values ('viagens');
INSERT INTO tb_categorias(nome) values ('bebidas alcoólicas');
INSERT INTO tb_categorias(nome) values ('especialidades');
INSERT INTO tb_categorias(nome) values ('gourmet');
INSERT INTO tb_categorias(nome) values ('escritório');
INSERT INTO tb_categorias(nome) values ('construção');
INSERT INTO tb_categorias(nome) values ('decor');
INSERT INTO tb_categorias(nome) values ('artigos esportivos');
INSERT INTO tb_categorias(nome) values ('pintura');
INSERT INTO tb_categorias(nome) values ('música');
INSERT INTO tb_categorias(nome) values ('empréstimos');

